import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class New_Account extends javax.swing.JFrame {
Statement st=null;
ResultSet rs=null;
    /**
     * Creates new form New_Account
     */
    public New_Account() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        T2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        T3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CB1 = new javax.swing.JComboBox<>();
        P1 = new javax.swing.JPasswordField();
        P2 = new javax.swing.JPasswordField();
        Submit_Btn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CB2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        T4 = new javax.swing.JTextField();
        T5 = new javax.swing.JTextField();
        L2 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        T8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        T7 = new javax.swing.JTextField();
        T6 = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        T2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T2ActionPerformed(evt);
            }
        });
        getContentPane().add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 200, -1));

        jLabel2.setText("Usename :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        getContentPane().add(T3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 200, -1));

        jLabel3.setText("Password :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel4.setText("Confirm Password :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel5.setText("Department :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        CB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Civil Engineering", "Computer Engineering", "Electrical Engineering", "Electronics And Communication Engineering", "Information Technology", "Mechanical Engineering" }));
        getContentPane().add(CB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 200, -1));

        P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1ActionPerformed(evt);
            }
        });
        getContentPane().add(P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 200, -1));

        P2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                P2FocusLost(evt);
            }
        });
        getContentPane().add(P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 200, -1));

        Submit_Btn.setText("Submit");
        Submit_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(Submit_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, -1, -1));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, -1, -1));

        jLabel6.setText("Registration No. :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 20));
        getContentPane().add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 200, -1));

        jLabel7.setText("Post :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        CB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Head Of Department", "Deputy Head Academics", "Deputy Head Administration", "Associate Professor", "Assistant Professor", "Technical Assistant" }));
        getContentPane().add(CB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 200, -1));

        jLabel8.setText("E-mail :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel9.setText("Mobile :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        T4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T4ActionPerformed(evt);
            }
        });
        getContentPane().add(T4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 200, -1));

        T5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T5ActionPerformed(evt);
            }
        });
        getContentPane().add(T5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 200, -1));

        L2.setForeground(new java.awt.Color(0, 204, 0));
        L2.setText("Matched");
        getContentPane().add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        L1.setForeground(new java.awt.Color(255, 0, 0));
        L1.setText("Not Matched");
        getContentPane().add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jLabel10.setText("Result:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));
        getContentPane().add(T8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 200, -1));

        jLabel11.setText("Tutor:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel12.setText("Subject:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        T7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T7ActionPerformed(evt);
            }
        });
        getContentPane().add(T7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 200, -1));

        T6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T6ActionPerformed(evt);
            }
        });
        getContentPane().add(T6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Submit_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_BtnActionPerformed
    try
    {
        Class.forName("java.sql.DriverManager");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/poornima","root","tiger");
        String reg,name,uname,pwd,dept,post,email,mob,sql,result,tutor,subject;
        reg=T1.getText();
        name=T2.getText();
        uname=T3.getText();
        pwd=new String(P2.getPassword());
        dept=(String)CB1.getSelectedItem();
        post=(String)CB2.getSelectedItem();
        email=T4.getText();
        mob=T5.getText();
        result=T6.getText();
        tutor=T7.getText();
        subject=T8.getText();
        sql="insert into Faculty values('"+reg+"','"+name+"','"+uname+"','"+pwd+"','"+dept+"','"+post+"','"+email+"',"+mob+",'"+result+"','"+tutor+"','"+subject+"')";
        st=con.createStatement();
        st.executeUpdate(sql);
        JOptionPane.showMessageDialog(null,"Record Saved.");        
    }
    catch(ClassNotFoundException | SQLException | HeadlessException e)
    {
        JOptionPane.showMessageDialog(null,"Error !!! "+e.getMessage());
    }

    }//GEN-LAST:event_Submit_BtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Login user=new Login();
user.setVisible(true);
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int cexit=JOptionPane.showConfirmDialog(null, "Do you really want to quit ?");
if(cexit==JOptionPane.YES_OPTION)
{
    JOptionPane.showMessageDialog(null,"Thank You for using this portal."+"\n"
                +"Have a nice day!"+"\n"
                +"powered by Team INFINITY");
    System.exit(0);
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void T5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T5ActionPerformed

    private void T2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T2ActionPerformed

    private void P2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_P2FocusLost
    String pwd1=new String(P1.getPassword());
    String pwd2=new String(P2.getPassword());
    if(pwd1.equals(pwd2))
    {
        L2.setVisible(true);
        L1.setVisible(false);
        Submit_Btn.setEnabled(true);
    }
    else
    {
        L1.setVisible(true);
        L2.setVisible(false);
    }
    }//GEN-LAST:event_P2FocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
L1.setVisible(false);
L2.setVisible(false);
Submit_Btn.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void T7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T7ActionPerformed

    private void T6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T6ActionPerformed

    private void T4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T4ActionPerformed

    private void P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_Account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB1;
    private javax.swing.JComboBox<String> CB2;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JPasswordField P1;
    private javax.swing.JPasswordField P2;
    private javax.swing.JButton Submit_Btn;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JTextField T6;
    private javax.swing.JTextField T7;
    private javax.swing.JTextField T8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
